// Molecule Reference Data (generated from molecule_reference.csv)
const MOLECULE_REFERENCE_DATA = [
  {
    "canonical_molecule": "ACP-204",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Selective antagonist/inverse agonist of 5-hydroxytryptamine (serotonin) receptor subtype 2A",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "ACADIA Pharmaceuticals Inc.ACADIA Pharmaceuticals Inc.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "ACADIA Pharmaceuticals Inc.",
    "matched_countries_ctgov": "Brazil|Bulgaria|Chile|Czechia|France|Italy|Mexico|Serbia|South Korea|Spain|Taiwan|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "AR1001",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "PDE-5 inhibitor; improve synaptic plasticity",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "AriBio Co., Ltd.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "AriBio Co., Ltd.",
    "matched_countries_ctgov": "Canada|China|Czechia|Denmark|France|Germany|Italy|Netherlands|Poland|South Korea|Spain|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Buntanetap",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Proteostasis/Proteinopathies",
    "mechanism_of_action": "Inhibits the translation of mRNA of amyloid precursor protein (APP), tau, α-synuclein, and other neurotoxic proteins",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Annovis Bio Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Dextromethorphan + Bupropion",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "NMDA receptor antagonist; combination of dextromethorphan and bupropion",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Axsome Therapeutics, Inc.Axsome Therapeutics, Inc.Axsome Therapeutics, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Dextromethorphan + Quinidine",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Sigma 1 receptor agonist; NMDA receptor antagonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Otsuka Pharmaceutical Development & Commercialization, Inc.Otsuka Pharmaceutical Development & Commercialization, Inc.Otsuka Pharmaceutical Development & Commercialization, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Donanemab",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Monoclonal antibody specific for pyroglutamate form of Aβ",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and CompanyEli Lilly and CompanyEli Lilly and CompanyEli Lilly and Company",
    "matched_ctgov_trials_count": "5",
    "matched_sponsors_ctgov": "Banner Health|Eli Lilly and Company|National Institute on Aging (NIA)|Universidad de Antioquia",
    "matched_countries_ctgov": "Argentina|Australia|Canada|China|Colombia|Czechia|Japan|Netherlands|Poland|Puerto Rico|South Korea|Spain|Taiwan|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Donepezil",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Acetylcholinesterase inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Assistance Publique - Hôpitaux de Paris",
    "matched_ctgov_trials_count": "4",
    "matched_sponsors_ctgov": "Assistance Publique - Hôpitaux de Paris|Duke University|France Alzheimer|National Institute on Aging (NIA)|Shanghai Jiao Tong University School of Medicine|Wanbangde Pharmaceutical Group Co., LTD",
    "matched_countries_ctgov": "France|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "E2814",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Tau",
    "mechanism_of_action": "Anti-tau monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of Medicine",
    "matched_ctgov_trials_count": "3",
    "matched_sponsors_ctgov": "Accelerating Medicines Partnership (AMP)|Alzheimer's Association|Avid Radiopharmaceuticals|Eisai Inc.|Eli Lilly and Company|Hoffmann-La Roche|Janssen, LP|National Institute on Aging (NIA)|Washington University School of Medicine",
    "matched_countries_ctgov": "Argentina|Australia|Brazil|Canada|Colombia|France|Germany|Ireland|Italy|Japan|Mexico|Netherlands|Puerto Rico|Spain|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "E2814 + Lecanemab",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Multi-target",
    "mechanism_of_action": "Anti-tau monoclonal antibody plus anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of Medicine",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Escitalopram",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Selective serotonin reuptake inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "JHSPH Center for Clinical Trials",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "JHSPH Center for Clinical Trials|National Institute on Aging (NIA)",
    "matched_countries_ctgov": "Canada|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Gantenerumab",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Monoclonal antibody directed at Aβ plaques and oligomers",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of MedicineWashington University School of Medicine",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Accelerating Medicines Partnership (AMP)|Alzheimer's Association|Avid Radiopharmaceuticals|Eisai Inc.|Eli Lilly and Company|Hoffmann-La Roche|Janssen, LP|National Institute on Aging (NIA)|Washington University School of Medicine",
    "matched_countries_ctgov": "Argentina|Australia|Brazil|Canada|Colombia|France|Germany|Ireland|Italy|Japan|Netherlands|Puerto Rico|Spain|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Gonadorelin",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Growth Factors and Hormones",
    "mechanism_of_action": "Anti-aging effects",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Nelly Pitteloud",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Guanfacine",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Alpha-2 adrenergic agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Imperial College London",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Imperial College London",
    "matched_countries_ctgov": "United Kingdom",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Lecanemab",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of MedicineEisai Inc.Eisai Inc.Washington University School of Medicine",
    "matched_ctgov_trials_count": "8",
    "matched_sponsors_ctgov": "Accelerating Medicines Partnership (AMP)|Alzheimer's Association|Alzheimer's Clinical Trials Consortium|Avid Radiopharmaceuticals|Biogen|Bristol-Myers Squibb|Eisai Inc.|Eli Lilly and Company|Hoffmann-La Roche|Janssen, LP|National Institute on Aging (NIA)|Neurology Office of South Florida|Washington University School of Medicine|Zhejiang Provincial People's Hospital",
    "matched_countries_ctgov": "Argentina|Australia|Brazil|Canada|China|Colombia|France|Germany|Ireland|Italy|Japan|Mexico|Netherlands|Puerto Rico|Russia|Singapore|South Korea|Spain|Sweden|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Masitinib",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Tyrosine kinase inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "AB Science",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "AB Science",
    "matched_countries_ctgov": "France|Spain",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Masupirdine",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "5-HT6 antagonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Suven Life Sciences Limited",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Suven Life Sciences Limited",
    "matched_countries_ctgov": "Croatia|Poland|Serbia|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Metformin",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Insulin sensitizer to improve CNS glucose metabolism",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Columbia University",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Nabilone",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Synthetic cannabinoid",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Sunnybrook Health Sciences Centre",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Alzheimer's Drug Discovery Foundation|Sunnybrook Health Sciences Centre",
    "matched_countries_ctgov": "Canada",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Nilotinib",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Proteostasis/Proteinopathies",
    "mechanism_of_action": "Tyrosine kinase inhibitor; autophagy enhancer; promotes clearance of Aβ and tau",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "KeifeRx, LLC",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Piromelatine",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Melatonin receptor agonist; 5-HT 1A and 1D serotonin receptor agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Neurim Pharmaceuticals Ltd.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Neurim Pharmaceuticals Ltd.|Syneos Health",
    "matched_countries_ctgov": "Canada|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "PM012",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurogenesis",
    "mechanism_of_action": "Upregulation of BDNF",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Mediforum Ltd., Co.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Remternetug",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody targeting the pyroglutamate form of A",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and CompanyWashington University School of MedicineEli Lilly and Company",
    "matched_ctgov_trials_count": "4",
    "matched_sponsors_ctgov": "Alzheimer's Association|Eli Lilly and Company|GHR Foundation|National Institute on Aging (NIA)|Private Donors|Washington University School of Medicine",
    "matched_countries_ctgov": "Argentina|Australia|Canada|China|Colombia|France|Germany|Italy|Japan|Mexico|Netherlands|New Zealand|Puerto Rico|South Korea|Spain|Taiwan|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Rotigotine + Rivastigmine",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Combined dopamine agonist and cholinesterase inhibition",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "I.R.C.C.S. Fondazione Santa Lucia",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Semaglutide",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "GLP-1 agonist; reduces neuroinflammation and improves insulin signaling in the brain",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Novo Nordisk A/SNovo Nordisk A/SNovo Nordisk A/S",
    "matched_ctgov_trials_count": "5",
    "matched_sponsors_ctgov": "Alzheimer's Association|Herlev Hospital|Imperial College London|Novo Nordisk A/S|Rune Skovgaard Rasmussen|Rutgers, The State University of New Jersey",
    "matched_countries_ctgov": "Argentina|Australia|Austria|Belgium|Brazil|Bulgaria|Canada|China|Croatia|Czechia|Denmark|Finland|France|Germany|Greece|Hungary|Ireland|Israel|Italy|Japan|Netherlands|Poland|Portugal|Romania|Russia|Serbia|Slovakia|Slovenia|South Africa|South Korea|Spain|Sweden|Switzerland|Taiwan|Turkey|Ukraine|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Simufilam",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Filamin A protein inhibitor; stabilizes amyloid-alpha-7 nicotinic receptor interaction",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Cassava Sciences, Inc.Cassava Sciences, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Solanezumab",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Monoclonal antibody directed at Aβ monomers",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of Medicine",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Accelerating Medicines Partnership (AMP)|Alzheimer's Association|Avid Radiopharmaceuticals|Eisai Inc.|Eli Lilly and Company|Hoffmann-La Roche|Janssen, LP|National Institute on Aging (NIA)|Washington University School of Medicine",
    "matched_countries_ctgov": "Argentina|Australia|Brazil|Canada|Colombia|France|Germany|Ireland|Italy|Japan|Netherlands|Puerto Rico|Spain|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Tertomotide",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "hTERT peptide vaccine; mimics extra-telomeric functions to inhibit neurotoxicity, apoptosis, and reactive oxygen species",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Samsung Pharmaceutical Co., Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Tricaprilin",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Caprylic triglyceride; induces ketosis and improves mitochondrial and neuronal function",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Cerecin",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Cerecin",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Valiltramiprosate",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Prodrug of tramiprosate; inhibits Aβ aggregation into toxic oligomers",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alzheon Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Wujia Yizhi",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Herbal mixture with effects on inflammation, apoptosis, calcium signaling",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Sichuan Jishengtang Pharmaceutical Co., Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Xanomeline + Trospium",
    "phase_from_cummings": "Phase 3",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Muscarinic cholinergic agonist with peripheral anticholinergic",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Karuna TherapeuticsKaruna TherapeuticsKaruna TherapeuticsKaruna Therapeutics",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "2-HOBA",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Oxidative Stress",
    "mechanism_of_action": "Scavenger for reactive carbonyl species",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "MTI Biotech Inc",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "50561",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "RAC1 inhibitor (RAC family small GTPase inhibitors) enhance dendritic spine morphogenesis and synaptic plasticity",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Beijing Joekai Biotechnology LLC",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ABBV-916",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "AbbVie",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ACI-24.060",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Vaccine stimulates antibodies against A",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "AC Immune SA",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ACI-35",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "Active immunotherapy targeting tau",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Janssen Pharmaceutica N.V., Belgium",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "AL002",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Monoclonal antibody targeting TREM2 receptors to promote microglial clearance of Aβ",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alector Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "AL101",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Proteostasis/Proteinopathies",
    "mechanism_of_action": "Monoclonal antibody to sortilin (SORT1) to improve lysosomal function",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "GlaxoSmithKline",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Aldesleukin",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Restore function of regulatory T cells",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Centre Hospitalier St AnneThe Methodist Hospital Research Institute",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ASN51",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "O-β-linked N-acetylglucosaminylation (O-GlcNAcylation) modulates tau phosphorylation and aggregation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Asceneuron S.A.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Astragalus",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Multi-target",
    "mechanism_of_action": "Traditional Chinese medicine",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Fujian Medical University Union HospitalFujian Medical University Union Hospital",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Fujian Medical University Union Hospital",
    "matched_countries_ctgov": "China",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Baricitinib",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Janus kinase inhibitor; reduces neuroinflammation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Massachusetts General Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "BCG vaccine",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Immunomodulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Steven E Arnold, MD",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Benfotiamine",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Synthetic thiamine to improve neuronal function",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alzheimer's Disease Cooperative Study (ADCS)",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Bepranemab",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "Anti-tau monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "UCB Biopharma SRL",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "BIIB080",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "Antisense oligonucleotide targeting tau expression; MAPT RNA inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Biogen",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Biogen",
    "matched_countries_ctgov": "Australia|Belgium|Canada|Czechia|Denmark|Finland|France|Germany|Italy|Japan|Netherlands|Poland|Spain|Sweden|Switzerland|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "BMS-986446",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "Reduces tau spread; directed at epitopes of the microtubule binding region (MTBR)",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Bristol-Myers Squibb",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Bristol-Myers Squibb",
    "matched_countries_ctgov": "Australia|Belgium|Canada|Japan|Singapore|South Korea|Spain|Sweden|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Brexanolone",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurogenesis",
    "mechanism_of_action": "Allosteric modulator of GABA-A receptors",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Arizona",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Brivaracetam",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Anticonvulsant with high affinity for synaptic vesicle protein 2A",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of California, Los Angeles",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "University of California, Los Angeles",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Bumetanide",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "APOE, Lipids and Lipoprotein Receptors",
    "mechanism_of_action": "Reversal of APOE-specific AD signatures",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Stanford University",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Stanford University",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Cannabidiol",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Cannabinoid with effects on cannabinoid receptors",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eastern Virginia Medical SchoolUniversity of Colorado, DenverSunnybrook Health Sciences Centre",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "University of Colorado, Denver",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Ciprofloxacin + Celecoxib",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Combined product targeting inflammation, iron accumulation, impaired RNA regulation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "NeuroSense Therapeutics Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Contraloid acetate",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Aggregation inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "PRInnovation GmbH",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "CORT108297",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Growth Factors and Hormones",
    "mechanism_of_action": "Selective glucocorticoid receptor antagonist; reduce neuroendocrine stress responses",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Johns Hopkins University",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Johns Hopkins University|Private Philanthropic Funds",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "CT1812",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Sigma-2 receptor antagonist; competes with oligomeric Aβ binding; protect against Aβ-induced synaptic toxicity",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Cognition Therapeutics",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Alzheimer's Clinical Trials Consortium|Cognition Therapeutics|National Institute on Aging (NIA)",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "DAOIB + AO",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Multi-target",
    "mechanism_of_action": "NMDA enhancement (DAOIB) + antioxidant",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Chang Gung Memorial Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Dasatinib + Quercetin",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Tyrosine kinase inhibitor (dasatinib) and flavonoid (quercetin); senolytic therapy approach to reduce senescent cells and tau aggregation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Wake Forest University Health SciencesMayo Clinic",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Dexmedetomidine",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Sublingual dexmedetomidine; selective α2-adrenergic receptor agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Teikoku Pharma USA, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Dimebon",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Improvement of mitochondrial function",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Bigespas LTD",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "E2814 + Lecanemab",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Multi-target",
    "mechanism_of_action": "Anti-tau monoclonal antibody plus anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eisai Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Edaravone",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Oxidative Stress",
    "mechanism_of_action": "Pyrazolone free-radical scavenger",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Treeway B.V.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Enrupatinib",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Colony stimulating factor 1 receptor (CSF-1R) selective inhibitor to modulate microglia",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Elixiron Immunotherapeutics Limited",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "EX039",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Inhibits D-amino acids oxidate to increase N-methyl-D-aspartate receptor activity",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Excelsior",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Excelsior|Formosa Biomedical Technology Corp.",
    "matched_countries_ctgov": "Taiwan",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Exercised plasma",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Plasma transfusion from exercise-trained donors",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Norwegian University of Science and Technology",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Fasudil",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Vasculature",
    "mechanism_of_action": "Vasodilator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Helse Stavanger HF",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Haraldsplass Deaconess Hospital|Helse Fonna|Helse Stavanger HF|St. Olavs Hospital|University Hospital, Akershus|University of Exeter",
    "matched_countries_ctgov": "Norway",
    "nordic_presence": "TRUE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Foralumab",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Anti-CDR3 antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Brigham and Women's Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "IGC-AD1",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Tetrahydrocannabinol that binds to the CB1 receptor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "IGC Pharma, LLC",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Insulin",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Decrease glucose resistance and increase insulin signaling in the brain",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Wake Forest University Health Sciences",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ITI-1284",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "A deuterated form of lumateperone; 5-HT2A receptor antagonist, D1 receptor modulator, D2 receptor modulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Intra-Cellular Therapies, Inc.Intra-Cellular Therapies, Inc.",
    "matched_ctgov_trials_count": "2",
    "matched_sponsors_ctgov": "Intra-Cellular Therapies, Inc.",
    "matched_countries_ctgov": "Bulgaria|Croatia|Czechia|Poland|Romania|Serbia|Slovakia|Spain|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "IVL3003",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Cholinesterase inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Inventage Lab., Inc.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Inventage Lab., Inc.",
    "matched_countries_ctgov": "Australia",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "JNJ-63733657",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "Monoclonal antibody targeting soluble tau",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Janssen Research & Development, LLC",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Janssen Research & Development, LLC",
    "matched_countries_ctgov": "Australia|Belgium|Canada|France|Japan|Netherlands|Spain|Sweden|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Lecanemab",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eisai Inc.",
    "matched_ctgov_trials_count": "8",
    "matched_sponsors_ctgov": "Accelerating Medicines Partnership (AMP)|Alzheimer's Association|Alzheimer's Clinical Trials Consortium|Avid Radiopharmaceuticals|Biogen|Bristol-Myers Squibb|Eisai Inc.|Eli Lilly and Company|Hoffmann-La Roche|Janssen, LP|National Institute on Aging (NIA)|Neurology Office of South Florida|Washington University School of Medicine|Zhejiang Provincial People's Hospital",
    "matched_countries_ctgov": "Argentina|Australia|Brazil|Canada|China|Colombia|France|Germany|Ireland|Italy|Japan|Mexico|Netherlands|Puerto Rico|Russia|Singapore|South Korea|Spain|Sweden|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Lemborexant",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Multiple",
    "mechanism_of_action": "Dual antagonist of orexin OX1 and OX2 receptors with potential effect on A and tau protein",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of Medicine",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Eisai Inc.|National Institute on Aging (NIA)|National Institutes of Health (NIH)|Washington University School of Medicine",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Lenalidomide",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Reduce inflammatory cytokines; modulate innate and adaptive immune responses",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "St. Joseph's Hospital and Medical Center, PhoenixSt. Joseph's Hospital and Medical Center, Phoenix",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "St. Joseph's Hospital and Medical Center, Phoenix|Texas Tech University",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Leuprolide",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Growth Factors and Hormones",
    "mechanism_of_action": "GnRH receptor agonist; reduce effects of elevated GnRH and gonadotropins on the brain",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Weill Medical College of Cornell University",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Levetiracetam",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "SV2A modulator; improve synaptic function; reduce Aβ-induced neuronal hyperactivity",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Beth Israel Deaconess Medical CenterWalter Reed National Military Medical CenterAgeneBio",
    "matched_ctgov_trials_count": "2",
    "matched_sponsors_ctgov": "Beth Israel Deaconess Medical Center|Fundació Institut de Recerca de l'Hospital de la Santa Creu i Sant Pau|Fundación CITA Alzheimer|Fundación de Investigación Biomédica - Hospital Universitario de La Princesa|Hospital Universitario Marqués de Valdecilla|University Hospital Virgen de las Nieves",
    "matched_countries_ctgov": "Spain|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "LY3372689",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Tau",
    "mechanism_of_action": "O-GlycNAcase inhibitor; promote tau glycosylation, prevent tau aggregation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and Company",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Memantine",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "NMDA receptor antagonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Virginia",
    "matched_ctgov_trials_count": "3",
    "matched_sponsors_ctgov": "Bigespas LTD|Duke University|National Institute on Aging (NIA)|University of Virginia",
    "matched_countries_ctgov": "Russia|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Mevidalen",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "DopamineD1 receptor - positive allosteric modulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and Company",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Eli Lilly and Company",
    "matched_countries_ctgov": "Japan|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "MIB-626",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Sirtuin-nicotinamide adenine dinucleotide stimulator to enhance alpha-secretase",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Brigham and Women's Hospital",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Brigham and Women's Hospital",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "MK-1167",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Undisclosed",
    "mechanism_of_action": "Undisclosed",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Merck Sharp & Dohme LLC",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Merck Sharp & Dohme LLC",
    "matched_countries_ctgov": "Argentina|Canada|Italy|Japan|Netherlands|South Korea|Spain|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Nicotinamide riboside",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Mitochondrial function enhancer and antioxidant",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Haukeland University Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Nicotine transdermal patch",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Nicotinic acetylcholine receptor agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Southern California",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Nicotinic Acid",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Engages the hydroxycarboxylic acid receptor 2 (HCAR2) on microglia to reduce plaque burden and neuronal dystrophy",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Indiana University",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "NP03",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Ion with effects on amyloid, oxidation, and inflammation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Medesis Pharma SA",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Polypill",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Undisclosed",
    "mechanism_of_action": "Undisclosed",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Noah Pharmaceuticals, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Rifaximin",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Gut-Brain Axis",
    "mechanism_of_action": "Antibiotic to change microbiome composition",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Jasmohan Bajaj",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "RO7269162",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Gamma-secretase modulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Hoffmann-La Roche",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Hoffmann-La Roche",
    "matched_countries_ctgov": "Chile|Denmark|France|Germany|Italy|Poland|South Korea|Spain|United Kingdom",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "RQC",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Prevent or reduce amyloid",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Zaparackas and Knepper LTD",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Sabirnetug",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Monoclonal antibody targeting soluble Aβ",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Acumen Pharmaceuticals",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Acumen Pharmaceuticals",
    "matched_countries_ctgov": "Canada|Germany|Spain|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Sargramostim",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Granulocyte macrophage colony stimulating factor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Colorado, Denver",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Alzheimer's Association|National Institute on Aging (NIA)|Partner Therapeutics, Inc.|University of Colorado, Denver",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Senicapoc",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Calcium-activated potassium channel blocker",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of California, Davis",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Alzheimer's Association|Alzheimer's Drug Discovery Foundation|Biossil Inc.|University of California, Davis",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "SHR-1707",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Shanghai Hengrui Pharmaceutical Co., Ltd.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Shanghai Hengrui Pharmaceutical Co., Ltd.",
    "matched_countries_ctgov": "China",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Simufilam",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Filamin A protein inhibitor; stabilizes amyloid-alpha-7 nicotinic receptor interaction to reduce neurodegeneration",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Cassava Sciences, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Siponimod",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Immunomodulation; sphingosine 1-phosphate receptor (S1P) modulator; prevents the egression of T lymphocytes from peripheral lymphoid organs; may inhibit neuroinflammation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "St. Joseph's Hospital and Medical Center, Phoenix",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Arizona State University|Laboratory Corporation of America|National Institute on Aging (NIA)|Novartis|St. Joseph's Hospital and Medical Center, Phoenix|Texas Tech University Health Sciences Center",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Sirolimus",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Vasculature",
    "mechanism_of_action": "Enhances cerebral blood flow; also, a mammalian target of rapamycin (mTOR) inhibitor with immunosuppressive effects",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "The University of Texas Health Science Center at San AntonioKarolinska Institutet",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "SPG302",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Increases the density of axospinous glutamatergic synapses",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Spinogenix",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Spinogenix",
    "matched_countries_ctgov": "Australia",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Suvorexant",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Multiple",
    "mechanism_of_action": "Dual orexin receptor antagonist; improved sleep with effects on CSF Aβ and tau",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Washington University School of Medicine",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Good Ventures|Merck Sharp & Dohme LLC|Washington University School of Medicine",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Tertomotide",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "hTERT peptide vaccine; mimics extra-telomeric functions to inhibit neurotoxicity, apoptosis, and reactive oxygen species",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "GemVax & Kael",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Trazodone",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Circadian Rhythm",
    "mechanism_of_action": "Serotonin reuptake inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Johns Hopkins University",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Johns Hopkins University|National Institute on Aging (NIA)",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Trontinemab",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody (gantenerumab) with enhanced blood-brain barrier penetration",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Hoffmann-La Roche",
    "matched_ctgov_trials_count": "2",
    "matched_sponsors_ctgov": "Hoffmann-La Roche",
    "matched_countries_ctgov": "Australia|Canada|China|Denmark|France|Germany|Italy|Japan|Poland|South Korea|Spain|Taiwan|United Kingdom|United States",
    "nordic_presence": "TRUE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "UE2343",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Growth Factors and Hormones",
    "mechanism_of_action": "11-β-hydroxysteroid dehydrogenase type 1 inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Actinogen Medical",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Valaciclovir",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Antiviral against HSV-1 and -2 infection; to prevent Aβ aggregation and plaque deposition",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Columbia University",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Valiltramiprosate",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Prodrug of tramiprosate; inhibits Aβ aggregation into toxic oligomers",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alzheon Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "XPro1595",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "TNF neutralizer to reduce neuroinflammation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Inmune Bio, Inc.Inmune Bio, Inc.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Inmune Bio, Inc.",
    "matched_countries_ctgov": "Australia",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Yangxue Qingnao",
    "phase_from_cummings": "Phase 2",
    "cadro_category": "Vasculature",
    "mechanism_of_action": "Cerebral blood flow enhancer",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Dongzhimen Hospital, Beijing",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ADEL-Y01",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Monoclonal antibody targeting tau tubulin to decrease tau aggregation and propagation and enhance microglial tau clearance",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alzheimer's Disease Expert Lab (ADEL), Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ALIA-1758",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-pyroglutamate amyloid antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Aliada Therapeutics",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ALN-APP",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "RNAi to decrease APP and downstream Aβ-related events",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alnylam Pharmaceuticals",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ALX-001",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "mGluR5 allosteric modulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Allyx TherapeuticsAllyx Therapeutics",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ALZ-101",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid vaccine",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Alzinova AB",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "APNmAb005",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Anti-tau monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "APRINOIA Therapeutics, LLC",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "AV-1959D",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid vaccine",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Institute for Molecular Medicine",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "BCG vaccine",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Immunomodulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Tamir Ben-Hur",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "BnH-015B",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter receptors",
    "mechanism_of_action": "Modulates GluN2B binding of NMDA receptors; Regulates BDNF/TRK-Beta and microglial-mediated IL-33-OPN signaling",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "BnH Research",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Brexanolone",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurogenesis",
    "mechanism_of_action": "Allosteric modulator of GABA-A receptors",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Arizona",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Cannabidiol",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter receptors",
    "mechanism_of_action": "Cannabinoid with effects on cannabinoid receptors",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Mclean Hospital",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "University of Colorado, Denver",
    "matched_countries_ctgov": "United States",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Centella asiatica",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Synaptic Plasticity/Neuroprotection",
    "mechanism_of_action": "Antioxidant and anti-inflammatory agent with synaptic and neuroprotective effects",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Oregon Health and Science University",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Choline",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Stabilizes the lipid metabolism and concomitantly restoring normal cell function by increasing phosphatidylcholine activity via the Kennedy pathway",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Paul E Schulz",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "CM383",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Keymed Biosciences Co.LtdKeymed Biosciences Co.Ltd",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "CpG1018",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Toll-like receptor nine agonist leading to reduced Aβ plaques and tau pathology",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "NYU Langone Health",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "CS6253",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "APOE, lipids and lipoprotein receptors",
    "mechanism_of_action": "Adenosine triphosphate-binding cassette transporter A1 (ABCA1) transfers lipids to ApoE, and increases clearance of amyloid beta from the brain",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Artery Therapeutics, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "DDN-A-0101",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Plaque reduction with reduced neuroinflammation and preserved synaptophysin",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Pharmacobio",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Donepezil",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter receptors",
    "mechanism_of_action": "Acetylcholinesterase inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "G2GBio, Inc.",
    "matched_ctgov_trials_count": "4",
    "matched_sponsors_ctgov": "Assistance Publique - Hôpitaux de Paris|Duke University|France Alzheimer|National Institute on Aging (NIA)|Shanghai Jiao Tong University School of Medicine|Wanbangde Pharmaceutical Group Co., LTD",
    "matched_countries_ctgov": "France|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Emraclidine",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter receptors",
    "mechanism_of_action": "M4-selective positive allosteric modulator",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Cerevel Therapeutics, LLC",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Emtricitabine",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "NRTI; reduce neuroinflammation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Butler Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "HHT201",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter receptors",
    "mechanism_of_action": "Cholinesterase inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Shanghai Synergy Pharmaceutical Sciences Co., Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "IBC-Ab002",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Anti-programmed death-ligand 1 (PD-L1) immune checkpoint inhibitor",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Immunobrain Checkpoint",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "ION269",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Antisense oligonucleotide directed at amyloid precursor protein",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Ionis Pharmaceuticals, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Leucettinib-21",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Antagonizes activity of the protein (DYRK1A protein kinase) derived from the DYRK1A gene to decrease tau hyperphosphorylation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Perha Pharmaceuticals",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "LY03017",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Undisclosed",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Luye Pharma Group Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "LY03020",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "A dual TAAR1/5-HT2CR agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Luye Pharma Group Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "LY3954068",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Undisclosed",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and Company",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "LY4006895",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Undisclosed",
    "mechanism_of_action": "Undisclosed",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and Company",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Mecamylamine",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter Receptors",
    "mechanism_of_action": "Nicotinic antagonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Vermont",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "MK-2214",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Anti-tau monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Merck Sharp & Dohme LLC",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Merck Sharp & Dohme LLC",
    "matched_countries_ctgov": "Argentina|Australia|Belgium|Japan|Netherlands|South Korea|Spain|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "Nicotinamide riboside",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Mitochondrial function enhancer and antioxidant",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Mclean Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "NIO752",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Anti-tau antisense oligonucleotide",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Novartis PharmaceuticalsUniversity College, London",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "NMRA-323511",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Growth Factors and Hormones",
    "mechanism_of_action": "Vasopressin V1a receptor antagonists",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Neumora Therapeutics, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "OLX-07010",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Tau",
    "mechanism_of_action": "Inhibits tau self-aggregation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Oligomerix, Inc",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Plasma exchange",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Anti-inflammatory",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Oslo University Hospital",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "PMN310",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Humanized immunoglobulin monoclonal antibody directed at oligomeric amyloid species",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "ProMis Neurosciences, Inc",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Probiotics",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Gut-brain Axis",
    "mechanism_of_action": "Inflammation/immunity",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Nicosia",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Psilocybin",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Neurotransmitter receptors",
    "mechanism_of_action": "Serotonin 2A receptor (5-HT2A) agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Johns Hopkins University",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Recombinant human serum albumin",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Oxidative Stress",
    "mechanism_of_action": "Antioxidant properties of albumin",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Protgen Ltd",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Remternetug",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Eli Lilly and Company",
    "matched_ctgov_trials_count": "4",
    "matched_sponsors_ctgov": "Alzheimer's Association|Eli Lilly and Company|GHR Foundation|National Institute on Aging (NIA)|Private Donors|Washington University School of Medicine",
    "matched_countries_ctgov": "Argentina|Australia|Canada|China|Colombia|France|Germany|Italy|Japan|Mexico|Netherlands|New Zealand|Puerto Rico|South Korea|Spain|Taiwan|United Kingdom|United States",
    "nordic_presence": "FALSE",
    "eu_presence": "TRUE"
  },
  {
    "canonical_molecule": "SHR-1707",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Amyloid beta",
    "mechanism_of_action": "Anti-amyloid monoclonal antibody",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Atridia Pty Ltd.",
    "matched_ctgov_trials_count": "1",
    "matched_sponsors_ctgov": "Shanghai Hengrui Pharmaceutical Co., Ltd.",
    "matched_countries_ctgov": "China",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "Sirolimus",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Vasculature",
    "mechanism_of_action": "Enhances cerebral blood flow; also a mammalian target of rapamycin (mTOR) inhibitor with immunosuppressive effects",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "University of Missouri-Columbia",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "TML-6",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "Synthetic curcumin analogue with anti-inflammatory properties; activates autophagy; reduces amyloid accumulation",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Merry Life Biomedical Co., Ltd.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "VG-3927",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Inflammation",
    "mechanism_of_action": "TREM2 agonist",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "Vigil Neuroscience, Inc.",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  },
  {
    "canonical_molecule": "VNA-318",
    "phase_from_cummings": "Phase 1",
    "cadro_category": "Metabolism and Bioenergetics",
    "mechanism_of_action": "Induction of mitophagy",
    "nct_ids": "",
    "lead_sponsor_from_cummings": "VANDRIA",
    "matched_ctgov_trials_count": "0",
    "matched_sponsors_ctgov": "",
    "matched_countries_ctgov": "",
    "nordic_presence": "FALSE",
    "eu_presence": "FALSE"
  }
];

// Helper function to find molecule by name (case-insensitive)
function findMoleculeReference(moleculeName) {
    if (!moleculeName) return null;
    const normalized = moleculeName.trim();
    return MOLECULE_REFERENCE_DATA.find(m => 
        m.canonical_molecule.toLowerCase() === normalized.toLowerCase()
    ) || null;
}
